#!/bin/sh
jsfiles=$(git diff --cached --name-only --diff-filter=ACM "*.js" "*.jsx" | tr '\n' ' ')

# Prettify all staged .js files
echo "$jsfiles" | xargs ./node_modules/.bin/prettier --write

# Lint all staged .js files
echo "$jsfiles" | xargs ./node_modules/.bin/eslint --fix
RESULT=$?
[ $RESULT -ne 0 ] && exit 1

# Add back the modified/prettified files to staging
echo "$jsfiles" | xargs git add

npm run test
RESULT=$?
[ $RESULT -ne 0 ] && exit 1
exit 0